// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Author struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Books []*Book `json:"books"`
}

type Book struct {
	ID     string  `json:"id"`
	Title  string  `json:"title"`
	Year   int     `json:"year"`
	Author *Author `json:"author"`
}

type Message struct {
	Message string `json:"Message"`
}

type NewBook struct {
	Title    string `json:"title"`
	Year     int    `json:"year"`
	AuthorID string `json:"authorId"`
}

type UpdateBook struct {
	ID       string `json:"id"`
	Title    string `json:"title"`
	Year     int    `json:"year"`
	AuthorID string `json:"authorId"`
}
